import { subDays, addDays, format } from 'date-fns'

const today = new Date()
const fmt = (d) => format(d, 'yyyy-MM-dd')

export const MATIERES = [
  { id: 'm1', nom: 'Mathématiques', code: 'MATH', couleur: '#3B82F6' },
  { id: 'm2', nom: 'Informatique', code: 'INFO', couleur: '#8B5CF6' },
  { id: 'm3', nom: 'Français', code: 'FR', couleur: '#10B981' },
  { id: 'm4', nom: 'Philosophie', code: 'PHILO', couleur: '#F59E0B' },
  { id: 'm5', nom: 'Anglais', code: 'ANG', couleur: '#EF4444' },
  { id: 'm6', nom: 'Économie', code: 'ECO', couleur: '#06B6D4' },
]

export const DEMO_USERS = [
  {
    id: 'u1',
    email: 'prof@demo.ci',
    password: 'demo1234',
    nom: 'M. Konan Yao',
    role: 'professeur',
    classe: 'BTS SIO 2024/2025',
  },
  {
    id: 'u2',
    email: 'delegue@demo.ci',
    password: 'demo1234',
    nom: 'Aya Kouamé',
    role: 'delegue',
    classe: 'BTS SIO 2024/2025',
  },
]

export const ENTREES_COURS = [
  {
    id: 'e1',
    matiere_id: 'm2',
    date: fmt(subDays(today, 1)),
    contenu: 'Introduction aux algorithmes de tri. Tri à bulles, tri par sélection et tri rapide. Complexité algorithmique O(n²) et O(n log n). Exercices pratiques sur Python.',
    professeur_nom: 'M. Konan Yao',
    created_by: 'u1',
    created_at: subDays(today, 1).toISOString(),
    document: {
      id: 'd1',
      nom: 'cours-algorithmes-tri.pdf',
      type: 'pdf',
      url: null,
      parties: [
        { id: 'p1', titre: '1. Introduction aux algorithmes', traitee: true },
        { id: 'p2', titre: '2. Tri à bulles', traitee: true },
        { id: 'p3', titre: '3. Tri par sélection', traitee: true },
        { id: 'p4', titre: '4. Tri rapide (Quicksort)', traitee: false },
        { id: 'p5', titre: '5. Comparaison des complexités', traitee: false },
      ],
    },
  },
  {
    id: 'e2',
    matiere_id: 'm1',
    date: fmt(subDays(today, 2)),
    contenu: 'Dérivation : règles fondamentales. Dérivées des fonctions usuelles (polynômes, trigonométriques, exponentielles). Règle de la chaîne et dérivées composées.',
    professeur_nom: 'Mme. Diabaté Fatou',
    created_by: 'u1',
    created_at: subDays(today, 2).toISOString(),
    document: {
      id: 'd2',
      nom: 'cours-derivation.pdf',
      type: 'pdf',
      url: null,
      parties: [
        { id: 'p1', titre: '1. Rappels sur les limites', traitee: true },
        { id: 'p2', titre: '2. Définition de la dérivée', traitee: true },
        { id: 'p3', titre: '3. Dérivées usuelles', traitee: true },
        { id: 'p4', titre: '4. Règle de la chaîne', traitee: false },
      ],
    },
  },
  {
    id: 'e3',
    matiere_id: 'm3',
    date: fmt(subDays(today, 3)),
    contenu: 'La dissertation philosophique : méthode et structure. Analyse du sujet, problématisation, plan dialectique. Exercice : « La liberté est-elle une illusion ? »',
    professeur_nom: 'M. Bamba Oumar',
    created_by: 'u1',
    created_at: subDays(today, 3).toISOString(),
    document: null,
  },
  {
    id: 'e4',
    matiere_id: 'm5',
    date: fmt(subDays(today, 4)),
    contenu: 'Business English: Writing professional emails. Formal vs informal tone. Opening and closing formulas. Practice exercises on email writing scenarios.',
    professeur_nom: 'Mme. Coulibaly Sarah',
    created_by: 'u1',
    created_at: subDays(today, 4).toISOString(),
    document: {
      id: 'd3',
      nom: 'business-english-emails.pdf',
      type: 'pdf',
      url: null,
      parties: [
        { id: 'p1', titre: '1. Formal vs Informal emails', traitee: true },
        { id: 'p2', titre: '2. Opening formulas', traitee: true },
        { id: 'p3', titre: '3. Email body structure', traitee: true },
        { id: 'p4', titre: '4. Closing & signatures', traitee: true },
        { id: 'p5', titre: '5. Practice exercises', traitee: false },
      ],
    },
  },
  {
    id: 'e5',
    matiere_id: 'm6',
    date: fmt(subDays(today, 5)),
    contenu: 'Microéconomie : offre et demande. Équilibre du marché concurrentiel. Élasticité-prix. Effets d\'une taxe ou d\'une subvention sur l\'équilibre.',
    professeur_nom: 'M. Touré Adama',
    created_by: 'u1',
    created_at: subDays(today, 5).toISOString(),
    document: null,
  },
  {
    id: 'e6',
    matiere_id: 'm2',
    date: fmt(subDays(today, 7)),
    contenu: 'Bases de données relationnelles. Modèle entité-association. Normalisation (1NF, 2NF, 3NF). Langage SQL : CREATE TABLE, INSERT, SELECT avec JOIN.',
    professeur_nom: 'M. Konan Yao',
    created_by: 'u1',
    created_at: subDays(today, 7).toISOString(),
    document: {
      id: 'd4',
      nom: 'cours-bdd-relationnelles.pdf',
      type: 'pdf',
      url: null,
      parties: [
        { id: 'p1', titre: '1. Introduction aux BDD', traitee: true },
        { id: 'p2', titre: '2. Modèle E-A', traitee: true },
        { id: 'p3', titre: '3. Normalisation', traitee: true },
        { id: 'p4', titre: '4. SQL de base', traitee: true },
        { id: 'p5', titre: '5. Jointures SQL', traitee: false },
        { id: 'p6', titre: '6. Exercices pratiques', traitee: false },
      ],
    },
  },
]

export const DEVOIRS = [
  {
    id: 'dv1',
    entree_id: 'e1',
    matiere_id: 'm2',
    description: 'Implémenter les trois algorithmes de tri en Python et comparer leurs temps d\'exécution sur un tableau de 10 000 éléments.',
    echeance: fmt(addDays(today, 3)),
    statut: 'a_faire',
    confirme_par: null,
    confirme_le: null,
  },
  {
    id: 'dv2',
    entree_id: 'e2',
    matiere_id: 'm1',
    description: 'Exercices p.87-89 du manuel : calculer les dérivées des fonctions f(x) et g(x). Corriger à l\'aide de la règle de la chaîne.',
    echeance: fmt(addDays(today, 1)),
    statut: 'a_faire',
    confirme_par: null,
    confirme_le: null,
  },
  {
    id: 'dv3',
    entree_id: 'e3',
    matiere_id: 'm3',
    description: 'Rédiger une introduction complète (300 mots) sur le sujet : « La technique libère-t-elle l\'homme ? »',
    echeance: fmt(subDays(today, 1)),
    statut: 'fait',
    confirme_par: 'u2',
    confirme_le: subDays(today, 1).toISOString(),
  },
  {
    id: 'dv4',
    entree_id: 'e4',
    matiere_id: 'm5',
    description: 'Write a formal email (150-200 words) applying for an internship at a tech company in Abidjan. Use the formulas from the lesson.',
    echeance: fmt(subDays(today, 2)),
    statut: 'fait',
    confirme_par: 'u2',
    confirme_le: subDays(today, 2).toISOString(),
  },
  {
    id: 'dv5',
    entree_id: 'e6',
    matiere_id: 'm2',
    description: 'Créer un schéma E-A pour une application de gestion d\'une bibliothèque scolaire et le normaliser jusqu\'en 3NF.',
    echeance: fmt(addDays(today, 5)),
    statut: 'a_faire',
    confirme_par: null,
    confirme_le: null,
  },
]
